service: prj-pub-csti
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/TokensTable"

functions:
  Health:
    handler: src/index.health
    events:
      - httpApi:
          path: /health
          method: get       
  addToken:
    handler: src/addToken.addToken
    events:
      - httpApi:
          path: /v2/tokens
          method: post
  getToken:
    handler: src/getToken.getToken
    events:
      - httpApi:
          path: /v2/tokens/{id}
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TokensTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH